# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Serdar Kuzucu
email: serdar.kuzucu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Serdar Kuzucu'nun kişisel blogu. Java, Javascript, Programlama
  ve birçok teknik konu üzerine kafa patlatmaca.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://serdarkuzucu.com" # the base hostname & protocol for your site
twitter_link: https://twitter.com/sedran
stackoverflow_link: http://stackoverflow.com/users/618279/sedran
linkedin_link: http://tr.linkedin.com/in/serdarkuzucu
facebook_link: https://www.facebook.com/srdrkzc
github_link: https://github.com/sedran
excerpt_separator: <!--more-->
template_version: 201904191944

google_search_url: http://www.google.com/search
google_search_domain: serdarkuzucu.com

# Build settings
markdown: kramdown
highlighter: rouge

# Any plugins within jekyll_plugin group from Gemfile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from
  - jekyll-archives

# Exclude these files from the build process results.
# Prevents them from showing up in the master branch which
# is the live site.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile

jekyll-archives:
  enabled:
    - categories
  layouts:
#    year: archive/year
#    month: archive/month
#    day: archive/day
#    tag: archive/tag
    category: category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tags/:name/'
    category: '/category/:name/'

pagination:
  enabled: true
  per_page: 12
  collection: 'posts'
  sort_reverse: true
  permalink: '/p/:num/'
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page
